### ISSUE TITLE
Endpoint /api/products returns null images

### ISSUE THREAD

**Issue by Trustacean** [vianneynara/kuenyawz-api#117]
endpoint /api/products doesnt returns null

/api/products
![image](https://github.com/user-attachments/assets/363da17d-2903-4ccd-8325-538c63897295)

/api/products/{productid}
![image](https://github.com/user-attachments/assets/0ec637ab-d293-49c3-9297-5fa61325fd9d)

**Comment by vianneynara** [comment]
Kill yourself
